### ISSUE TITLE
.bed files requested

### ISSUE THREAD

**Issue by anton-khodak** [roryk/tiny-test-data#5]
I'm looking for test data in [BED](https://www.broadinstitute.org/software/igv/BED) file format, it would be nice to have a sample in this repo.

**Comment by roryk** [comment]
Thanks Anton, I added a BED file to the Hsapiens genome. It is just the BEDified coordinates of all features in the ref-transcripts.gtf file in that directory. Hope that helps. Good luck with your studies.
